name: check-in

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 30 5 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: CheckIn
        run: |
          python ./main.py
        env:
          BARKTOKEN: ${{ secrets.BARKTOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          PHONE: ${{ secrets.PHONE }}
